language: r
r:
  - oldrel 
  - release
sudo: required
warnings_are_errors: false
r_packages:
  - devtools
  - covr
after_success:
  - Rscript -e 'covr::codecov()'
# blocklist
branches:
  except:
  - binder
